src/Entity/Internship.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InternshipRepository")
 */
class Internship
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="internships")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="internships")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact;

    /**
     * @ORM\Column(type="date")
     */
    private $startedOn;

    /**
     * @ORM\Column(type="date")
     */
    private $finishedOn;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addedOn;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedOn;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(?string $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getStartedOn(): ?\DateTimeInterface
    {
        return $this->startedOn;
    }

    public function setStartedOn(\DateTimeInterface $startedOn): self
    {
        $this->startedOn = $startedOn;

        return $this;
    }

    public function getFinishedOn(): ?\DateTimeInterface
    {
        return $this->finishedOn;
    }

    public function setFinishedOn(\DateTimeInterface $finishedOn): self
    {
        $this->finishedOn = $finishedOn;

        return $this;
    }

    public function setDuration() : self
    {
        $deltaT = date_diff($this->finishedOn->modify('+14 days'), $this->startedOn); // Arrondi au mois le plus proche
        $this->duration = $deltaT->m;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function getAddedOn(): ?\DateTimeInterface
    {
        return $this->addedOn;
    }

    public function setAddedOn(\DateTimeInterface $addedOn): self
    {
        $this->addedOn = $addedOn;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getPublishedOn(): ?\DateTimeInterface
    {
        return $this->publishedOn;
    }

    public function setPublishedOn(?\DateTimeInterface $publishedOn): self
    {
        $this->publishedOn = $publishedOn;

        return $this;
    }
}

src/Entity/SearchUser.php
<?php


namespace App\Entity;


class SearchUser
{
    /**
     * @var string|null
     */
    private $userName;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $LastName;

    /**
     * @param string|null $userName
     */
    public function setUserName(?string $userName): void
    {
        $this->userName = $userName;
    }

    /**
     * @return string|null
     */
    public function getUserName(): ?string
    {
        return $this->userName;
    }

    /**
     * @param string|null $firstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @param string|null $LastName
     */
    public function setLastName(?string $LastName): void
    {
        $this->LastName = $LastName;
    }

    /**
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->LastName;
    }
}

src/Form/InternshipType.php
<?php

namespace App\Form;

use App\Entity\Internship;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InternshipType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('city')
            ->add('postalCode')
            ->add('country')
            ->add('company')
            ->add('contact')
            ->add('startedOn', DateType::class,[
                "format"=>"dd/MM/yyyy",
                'widget' => 'single_text',
                'label' => 'Date de début'
            ])
            ->add('finishedOn',DateType::class, [
                "format"=>"dd/MM/yyyy",
                'widget' => 'single_text',
                'label' => 'Date de fin'
            ])
            ->add('category' )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Internship::class,
        ]);
    }
}

src/Controller/InternshipController.php
<?php

namespace App\Controller;

use App\Entity\Internship;
use App\Entity\SearchInternship;
use App\Form\InternshipType;
use App\Form\SearchInternshipType;

use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class InternshipController extends AbstractController
{
    /**
     * @Route("/stages", name="internships")
     * @Security("is_granted('ROLE_USER')")
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $search = new SearchInternship();
        $form = $this->createForm(SearchInternshipType::class, $search);
        $form->handleRequest($request);

        $qb = $this->getDoctrine()->getManager()->createQueryBuilder();
        $qb->select('i')
            ->from('App:Internship', 'i')
            ->andwhere('i.visible = 1');

        if($search->getCategory())
        {
            $qb = $qb->andWhere('i.category = :category')
                ->setParameter('category', '%'.$search->getCategory().'%');
        }

        if($search->getTitle())
        {
            $qb = $qb->andWhere('i.title LIKE :title')
                ->setParameter('title', '%'.$search->getTitle().'%');
        }

        if($search->getCompany())
        {
            $qb = $qb->andWhere('i.company LIKE :company')
                ->setParameter('company', '%'.$search->getCompany().'%');
        }

        if($search->getCountry())
        {
            $qb = $qb->andWhere('i.country LIKE :country')
                ->setParameter('country', '%'.$search->getCountry().'%');
        }

        if($search->getCity())
        {
            $qb = $qb->andWhere('i.city LIKE :city')
                ->setParameter('city', '%'.$search->getCity().'%');
        }

        if($search->getDuration())
        {
            $qb = $qb->andWhere('i.duration LIKE :duration')
                ->setParameter('duration', '%'.$search->getDuration().'%');
        }

        $query = $qb->getQuery()->getResult();

        $stages = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('internship/index.html.twig', [
            'stages' => $stages,
            'form' => $form->createView()]);
    }

    /**
     * @Route("/mes_stages", name="internships_my")
     * @Security("is_granted('ROLE_USER')")
     */
    public function internships()
    {
        $user = $this->getUser();
        $stages = $this->getDoctrine()->getRepository(Internship::class)->findBy(['author' => $user]);

        return $this->render('internship/internships.html.twig', ['stages' => $stages]);
    }

    /**
     * @Route("/stage/{id}", name="internship")
     * @Security("is_granted('view', stage)")
     */
    public function stage(Internship $stage, PaginatorInterface $paginator, Request $request)
    {
        $stages = $paginator->paginate(
            $this->getDoctrine()->getRepository(Internship::class)->getAlike($stage),
            $request->query->getInt('page', 1),
            4
        );

        return $this->render('internship/internship.html.twig', [
            'stage' => $stage,
            'stages' => $stages
            ]);
    }

    /**
     * @Route("/internship/new", name="internship_new")
     * @Security("is_granted('ROLE_USER')")
     */
    public function internshipNew(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $internship = new Internship();
        $form = $this->createForm(InternshipType::class, $internship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $internship->setAuthor($this->getUser())
                ->setDuration()
                ->setAddedOn(new \DateTime())
                ->setVisible(False);

            $entityManager->persist($internship);
            $entityManager->flush();

            $this->addFlash('success','Votre stage a bien été ajouté');
            return $this->redirectToRoute('internships_my');
        }

        return $this->render('internship/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/internship/{id}/edit", name="internship_edit")
     * @Security("is_granted('edit', internship)")
     */
    public function internshipEdit(Internship $internship, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $form = $this->createForm(InternshipType::class, $internship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            if (!$this->isGranted('ROLE_MODO')) {
                $internship->setVisible(False);
            }

            $entityManager->persist($internship);
            $entityManager->flush();

            $this->addFlash('success','Votre stage a bien été modifié');
            return $this->redirectToRoute('internships_my');
        }

        return $this->render('internship/edit.html.twig', [
            'form' => $form->createView(),
            'stage' => $internship
        ]);
    }

    /**
     * @Route("/internship/{id}/remove", name="internship_remove", methods={"POST"})
     * @Security("is_granted('edit', internship)")
     */
    public function internshipRemove(Internship $internship, Request $request)
    {
        if($request->request->get('token') && $this->isCsrfTokenValid('remove', $request->request->get('token'))){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($internship);
            $entityManager->flush();

            if($this->getUser() == $internship->getAuthor()) {
                $this->addFlash('success', 'Votre stage a bien été supprimé');
                return $this->redirectToRoute('home');
            }
            else {
                $this->addFlash('success', "Le stage {$internship->getTitle()} a bien été supprimé");
                return $this->redirectToRoute('internships_validation');
            }
        }

        return new JsonResponse(['error' => 'Invalid csrf token.'], 403);
    }
}

templates/internship/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{% block titre_page %}BDD Stages - {{ stage.title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header bg-green">
                    <h2>{{ stage.title }} <span data-target="#remove" data-toggle="modal"><i class="far fa-trash-alt"></i></span></h2>
                </div>

                <div class="body">
                    {{ form_start(form) }}
                    <div class="form-group">
                        {{ form_row(form.title, {'label': 'Titre', 'attr': {'class': 'form-control'}}) }}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="grey">Catégorie *</div>
                                {{ form_row(form.category, {'label': 'Catégorie', 'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">{{ form_row(form.company, {'label': 'Entreprise / Laboratoire', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-6">{{ form_row(form.contact, {'label': 'Contact', 'attr': {'class': 'form-control'}}) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">{{ form_row(form.country, {'label': 'Pays', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-4">{{ form_row(form.city, {'label': 'Ville', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-4">{{ form_row(form.postalCode, {'label': 'Code Postal', 'attr': {'class': 'form-control'}}) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">{{ form_widget(form.startedOn) }}</div>
                            <div class="col-md-4">{{ form_row(form.finishedOn) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="grey">Description *</div>
                                {{ form_row(form.description) }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Soumettre</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="remove">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    Etes-vous sur de vouloir supprimer {{ form.vars.value.title }} !
                </div>
                <div class="modal-footer">
                    <form action="{{ path('internship_remove', {'id': form.vars.value.id}) }}" method="post">
                        <input type="hidden" name="token" value="{{ csrf_token('remove') }}"/>
                        <button class="btn bg-monVert">OUI</button>
                        <button class="btn bg-monVert" data-dismiss="modal">NON</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/internship/index.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{% block titre_page %}BDD Stages - Stages{% endblock %}

{% block content %}
    <div class="card">
        <div class="header bg-green">
            <h2>Liste des Stages</h2>
        </div>

        <div class="body">
            {{ form_start(form) }}
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-4">{{ form_row(form.category, {'label': 'Catégorie'}) }}</div>
                        <div class="col-md-4">{{ form_row(form.title, {'label': 'Titre', 'attr': {'class': 'form-control'}}) }}</div>
                        <div class="col-md-4">{{ form_row(form.company, {'label': 'Entreprise / Laboratoire', 'attr': {'class': 'form-control'}}) }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">{{ form_row(form.country, {'label': 'Pays', 'attr': {'class': 'form-control'}}) }}</div>
                        <div class="col-md-4">{{ form_row(form.city, {'label': 'Ville', 'attr': {'class': 'form-control'}}) }}</div>
                        <div class="col-md-2">{{ form_row(form.duration, {'label': 'Durée', 'attr': {'class': 'form-control'}}) }}</div>
                        <div class="col-md-2"><button type="submit" class="btn btn-success">Rechercher</button></div>
                    </div>
                </div>
            {{ form_end(form) }}
            <div class="table-responsive">
                <table class="table table-stripped" id="sortable">
                    <thead>
                        <tr>
                            <th{% if stages.isSorted('category') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Catégorie', 'category') }}
                            </th>
                            <th{% if stages.isSorted('title') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Stage', 'title') }}
                            </th>
                            <th{% if stages.isSorted('company') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Entreprise / Laboaratoire', 'company') }}
                            </th>
                            <th{% if stages.isSorted('city') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Ville', 'city') }}
                            </th>
                            <th{% if stages.isSorted('country') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Pays', 'country') }}
                            </th>
                            <th{% if stages.isSorted('duration') %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(stages, 'Durée', 'duration') }}
                            </th>
                        </tr>
                    </thead>

                    {% for stage in stages %}
                        <tr>
                            <td>{{ stage.category.name }}</td>
                            <td>
                                <a href="/stage/{{ stage.id }}">{{ stage.title }}</a>
                                {% if is_granted('edit', stage) %}
                                    <a href="{{ path('internship_edit', {'id': stage.id}) }}"><i class="material-icons" style="font-size: 14px">edit</i></a>
                                {% endif %}
                            </td>
                            <td>{{ stage.company }}</td>
                            <td>{{ stage.city }}</td>
                            <td>{{ stage.country }}</td>
                            <td>{{ stage.duration }} mois</td>
                        </tr>
                    {% endfor %}
                </table>

                <div class="navigation">
                    {{ knp_pagination_render(stages) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/internship/internship.html.twig
{% extends 'base.html.twig' %}

{% block titre_page %}BDD Stages - {{ stage.title }}{% endblock %}

{% block content %}
    <div class="card">
        <div class="header bg-green">
            <h2>{{ stage.title }}
                {% if is_granted('edit', stage) %}
                    <a href="{{ path('internship_edit', {'id': stage.id}) }}"><i class="material-icons" style="font-size: 16px">edit</i></a>
                {% endif %}</h2>
        </div>

        <div class="body">
            <div class="row">
                <div class="col-md-6"><p class="font-bold">Etudiant</p> {{ stage.author.firstName }} {{ stage.author.lastName }}</div>
                <div class="col-md-3"><p class="font-bold">Catégorie</p> {{ stage.category.name }}</div>
                <div class="col-md-3"><p class="font-bold">Durée</p> {{ stage.duration }} mois</div>
            </div>

            <div class="row">
                <div class="col-md-6"><p class="font-bold">Entreprise</p> {{ stage.company }}</div>
                <div class="col-md-3"><p class="font-bold">Pays</p> {{ stage.country }}</div>
                <div class="col-md-3"><p class="font-bold">Ville / Code Postal</p> {{ stage.city }} {{ stage.postalCode }}</div>
            </div>

            <div class="row">
                <div class="col-md-6"><p class="font-bold">Contact</p> {{ stage.contact }}</div>
                <div class="col-md-3"><p class="font-bold">Début</p> {{ stage.startedOn | date('d/m/Y') }}</div>
                <div class="col-md-3"><p class="font-bold">Fin</p> {{ stage.finishedOn | date('d/m/Y') }}</div>
            </div>
            <div class="row">
                <div class="col-md-12"><p class="font-bold">Description</p> {{ stage.description }}</div>
            </div>
        </div>
    </div>

    <div class="of_card">
        <div class="header bg-green">
            <h2>Stages Similaires</h2>
        </div>

        <div class="body">
            <div class="row">
                {% for s in stages %}
                    <div class="col-md-3">
                        <div class="card">
                            <div class="header bg-green">
                                <h2>
                                    <a href="/stage/{{ s.id }}">{{ s.title }}</a>
                                    {% if is_granted('edit', s) %}
                                        <a href="{{ path('internship_edit', {'id': s.id}) }}"><i class="material-icons" style="font-size: 14px">edit</i></a>
                                    {% endif %}
                                    <small>{{ s.category }} / {{ s.duration }} mois<br>
                                        {{ s.company }}<br>
                                        {{ s.city }} {{ s.postalCode }}, {{ s.country }}</small>
                                </h2>
                            </div>

                            <div class="body">
                                {{ s.description }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="navigation">
            {{ knp_pagination_render(stages) }}
        </div>
    </div>
{% endblock %}

templates/internship/internships.html.twig
{% extends 'base.html.twig' %}

{% block titre_page %}BDD Stages - Mes Stages{% endblock %}

{% block content %}
    <div class="of_card">
        <div class="header bg-green">
            <h2>Mes Stages</h2>
        </div>

        <div class="body" id="grid">
            {% for s in stages %}
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-green">
                            <h2>
                                <a href="/stage/{{ s.id }}">{{ s.title }}</a>
                                {% if s.visible %}
                                    <i class="material-icons" style="font-size: 18px">visibility</i>
                                {% else %}
                                    <i class="material-icons" style="font-size: 18px">visibility_off</i>
                                {% endif %}
                                {% if is_granted('edit', s) %}
                                    <a href="{{ path('internship_edit', {'id': s.id}) }}"><i class="material-icons" style="font-size: 18px">edit</i></a>
                                {% endif %}
                                <small>{{ s.category }} / {{ s.duration }} mois<br>
                                    {{ s.company }}<br>
                                    {{ s.city }} {{ s.postalCode }}, {{ s.country }}</small>
                            </h2>
                        </div>

                        <div class="body">
                            {{ s.description }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/internship/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{% block titre_page %}BDD Stages - Nouveau Stage{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header bg-green">
                    <h2>Nouveau Stage</h2>
                </div>

                <div class="body">
                    {{ form_start(form) }}
                    <div class="form-group">
                        {{ form_row(form.title, {'label': 'Titre', 'attr': {'class': 'form-control'}}) }}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="grey">Catégorie *</div>
                                {{ form_row(form.category, {'label': 'Catégorie', 'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">{{ form_row(form.company, {'label': 'Entreprise / Laboratoire', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-6">{{ form_row(form.contact, {'label': 'Contact', 'attr': {'class': 'form-control'}}) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">{{ form_row(form.country, {'label': 'Pays', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-4">{{ form_row(form.city, {'label': 'Ville', 'attr': {'class': 'form-control'}}) }}</div>
                            <div class="col-md-4">{{ form_row(form.postalCode, {'label': 'Code Postal', 'attr': {'class': 'form-control'}}) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">{{ form_widget(form.startedOn) }}</div>
                            <div class="col-md-4">{{ form_row(form.finishedOn) }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="grey">Description *</div>
                                {{ form_row(form.description) }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Soumettre</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}